# Generated by Django 5.0 on 2023-12-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('user_name', models.CharField(max_length=20, verbose_name='昵称')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('says', models.CharField(blank=True, max_length=100, null=True, verbose_name='个性签名')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.SmallIntegerField()),
                ('message_source', models.SmallIntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
                ('source', models.SmallIntegerField()),
                ('forward', models.SmallIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ouruser')),
            ],
            options={
                'verbose_name_plural': 'messages',
            },
        ),
    ]
