# Generated by Django 5.0 on 2024-01-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visited',
            field=models.SmallIntegerField(default=0),
        ),
    ]
