# Generated by Django 5.0 on 2024-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='temp_name',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
